In [2]:
# Create a forward prop, back prop and gradient descent
# Using numpy and pandas 

import pandas as pd
import numpy as np



In [68]:
data_size = 20
input_data = np.random.rand(data_size,4)
print(input)
label = np.random.randint(0,2,size = data_size)
print(label)

[[0.52480162 0.90751461 0.08562624 0.8877006 ]
 [0.32352666 0.06406996 0.42215198 0.83664668]
 [0.15538677 0.85168924 0.09790202 0.60626888]
 [0.40625755 0.92009818 0.41776366 0.79395252]
 [0.04124228 0.50825002 0.69123443 0.5091974 ]
 [0.47092465 0.88435548 0.07281662 0.53565106]
 [0.58628394 0.72889282 0.77559055 0.08574807]
 [0.80145614 0.24664979 0.24786368 0.48439403]
 [0.29673186 0.01592657 0.42907099 0.30087965]
 [0.11790448 0.85025958 0.87179089 0.34793621]]
[1 0 0 0 0 1 0 1 0 1 1 1 0 0 1 1 0 1 1 1]


In [92]:

class gradientDescent():
    
    def __init__(self, num_layer, grad_step, input_data):
        self.grad_step = grad_step
        self.num_iter = num_iter
        self.input_data = input_data
        input_features = input_data.shape[1]
        self.w1 = np.random.rand(input_features, num_layer) 
        self.w2 = np.random.rand(num_layer, 1)
        
    def sigmoid(self, z):
        sig = 1/(1+ np.exp(-z))
        return sig

    def forwardProp(self, input_mat):
        # output= input %*% weight
        # w1 = 4x2, w2 = 2x1
        z1 = np.matmul(input_mat, self.w1) # 10 x 2
        self.h1 = self.sigmoid(z1) # 10 x 2
        # layer %*% weight
        # activation, sigmoid 
        # 1/(1+ exp(-x))
        z2 = np.matmul(self.h1, self.w2)
        yhat = sigmoid(z2)  # 
        return yhat


    def backProp(self, label , output, input_mat):
        # backprop is equal to 
        # h = label - prediction
        # derivative dJ/dz2, where yhat = sigmoid(z2) 
        d1 = output - label # 10 x 1 

        # derivative dJ/dw2
        w2_grad = np.matmul(self.h1.T, d1)  # 2 x 1

        # derivative dJ/dw1
        d2 = np.matmul(d1, self.w2.T) # 10 x 2
        
        h1_deriv = self.h1*(1-self.h1)
        d3 = d2 * h1_deriv  # 10 x 2 
        w1_grad = np.matmul(input_mat.T, d3) # 4 x 2 
        return w1_grad, w2_grad


    def calcCost(self, label, output):
        # calculate the cost 
        ce = label*np.log(output) + (1-label)*np.log(1- output)
        cost = np.sum(-ce)
        print('total cost = %f' % cost)

    def forwardBackProp(self, label, input_mat):
        output = self.forwardProp(input_mat)
        calcCost(label, output)
        w1_grad, w2_grad = self.backProp(label, output, input_mat)
        self.w1+= - w1_grad* self.grad_step 
        self.w2+= - w2_grad* self.grad_step 
        return output


    def iterForwardBackProp(self, label, num_iter):
        self.num_iter = num_iter
        self.label = np.expand_dims(label, axis=1)
        print('initial prediction')
        print(self.forwardProp(self.input_data))
        for i in range(1, self.num_iter):
            output = self.forwardBackProp(self.label, self.input_data)
        return self.w1, self.w2, output


num_layer = 1
grad_step = 1
num_iter = 50

grad = gradientDescent(num_layer = num_layer, grad_step= grad_step, input_data= input_data)
w1, w2, output = grad.iterForwardBackProp(label, num_iter)
print('weight')
print(w1.shape)
print(w2.shape)
print('label')
print(label)
print('output')
print(output)

initial prediction
[[0.55947022]
 [0.56657808]
 [0.56987152]
 [0.56493328]
 [0.57477014]
 [0.57004909]
 [0.5743703 ]
 [0.57507578]
 [0.57230137]
 [0.57744128]
 [0.58022675]
 [0.56193241]
 [0.57052532]
 [0.58459734]
 [0.57413423]
 [0.56969226]
 [0.57549139]
 [0.57686635]
 [0.57310215]
 [0.57872297]]
total cost = 13.788369
total cost = 13.816603
total cost = 13.889927
total cost = 14.054894
total cost = 14.310339
total cost = 14.445261
total cost = 13.981686
total cost = 13.756552
total cost = 13.713374
total cost = 13.689112
total cost = 13.662284
total cost = 13.632448
total cost = 13.598921
total cost = 13.560748
total cost = 13.516693
total cost = 13.465268
total cost = 13.404828
total cost = 13.333743
total cost = 13.250664
total cost = 13.154830
total cost = 13.046320
total cost = 12.926158
total cost = 12.796235
total cost = 12.659086
total cost = 12.517576
total cost = 12.374588
total cost = 12.232750
total cost = 12.094246
total cost = 11.960733
total cost = 11.833339
total cost

In [100]:
# Logistic Regression 

class LogisticRegression():
    
    def __init__(self,  grad_step):
        self.grad_step = grad_step
        
    def sigmoid(self, z):
        sig = 1/(1+ np.exp(-z))
        return sig

    def forwardProp(self, input_mat):
        # output= input %*% weight
        # w1 = 4x2, w2 = 2x1
        z1 = np.matmul(input_mat, self.w1) # 10 x 2
        yhat = self.sigmoid(z1) # 10 x 2
        # layer %*% weight
        # activation, sigmoid 
        # 1/(1+ exp(-x))
        return yhat


    def backProp(self, label , output, input_mat):
        # backprop is equal to 
        # h = label - prediction
        # derivative dJ/dz2, where yhat = sigmoid(z2) 
        d1 = output - label # 10 x 1 

        # derivative dJ/dw2
        w1_grad = np.matmul(input_mat.T, d1) # 4 x 2 
        return w1_grad


    def calcCost(self, label, output):
        # calculate the cost 
        ce = label*np.log(output) + (1-label)*np.log(1- output)
        cost = np.sum(-ce)
        print('total cost = %f' % cost)

    def forwardBackProp(self, label, input_mat):
        output = self.forwardProp(input_mat)
        calcCost(label, output)
        w1_grad = self.backProp(label, output, input_mat)
        self.w1+= - w1_grad* self.grad_step 
        return output


    def iterForwardBackProp(self, label, input_data, num_iter):
        self.num_iter = num_iter
        input_features = input_data.shape[1]
        self.w1 = np.random.rand(input_features, 1) 
        self.label = np.expand_dims(label, axis=1)
        print('initial prediction')
        print(self.forwardProp(input_data))
        
        for i in range(1, self.num_iter):
            output = self.forwardBackProp(self.label, input_data)
        return self.w1, output


grad_step =.1
logit = LogisticRegression(grad_step= grad_step)
w1, output = logit.iterForwardBackProp(label, input_data, num_iter)

print(w1)
print(label)
print(output)
# create the algo for logistic regression 

initial prediction
[[0.58762534]
 [0.66831247]
 [0.68900606]
 [0.64438487]
 [0.7766326 ]
 [0.70176528]
 [0.72197841]
 [0.77556508]
 [0.73597212]
 [0.78326323]
 [0.8066096 ]
 [0.63595025]
 [0.72149169]
 [0.83279933]
 [0.72582709]
 [0.6781753 ]
 [0.75739709]
 [0.7692368 ]
 [0.73710098]
 [0.77050864]]
total cost = 15.488048
total cost = 14.386510
total cost = 13.924371
total cost = 13.696432
total cost = 13.540483
total cost = 13.407103
total cost = 13.282855
total cost = 13.164168
total cost = 13.050018
total cost = 12.940026
total cost = 12.833979
total cost = 12.731710
total cost = 12.633065
total cost = 12.537902
total cost = 12.446082
total cost = 12.357473
total cost = 12.271947
total cost = 12.189382
total cost = 12.109662
total cost = 12.032673
total cost = 11.958307
total cost = 11.886462
total cost = 11.817037
total cost = 11.749937
total cost = 11.685072
total cost = 11.622353
total cost = 11.561698
total cost = 11.503025
total cost = 11.446259
total cost = 11.391324
total cost